#!/bin/sh -e
[ -f "$REPO_ROOT/.busybox" ] && exit 0

export TARGET=""

cd $SOURCES/busybox-$BUSYBOX_VER

$MAKE CC=$CC CFLAGS=-O0 LDFLAGS= STRIP=llvm-strip defconfig
$MAKE CC=$CC CFLAGS=-O0 LDFLAGS= STRIP=llvm-strip -j1
$MAKE CC=$CC CFLAGS=-O0 LDFLAGS= STRIP=llvm-strip install

rm _install/linuxrc
rm _install/bin/ln
rm _install/bin/uname
rm _install/usr/bin/install
rm _install/usr/bin/lspci
rm _install/bin/cat
rm _install/bin/chattr
rm _install/bin/chgrp
rm _install/bin/chmod
rm _install/bin/chown
rm _install/bin/cp
rm _install/bin/cpio
rm _install/bin/date
rm _install/bin/dmesg
rm _install/bin/dnsdomainname
rm _install/bin/echo
rm _install/bin/egrep
rm _install/bin/false
rm _install/bin/fgrep
rm _install/bin/fsync
rm _install/bin/grep
rm _install/bin/hostname
rm _install/bin/kill
rm _install/bin/login
rm _install/bin/ls
rm _install/bin/lsattr
rm _install/bin/mkdir
rm _install/bin/mknod
rm _install/bin/mktemp
rm _install/bin/mount
rm _install/bin/mountpoint
rm _install/bin/mv
rm _install/bin/netstat
rm _install/bin/nice
rm _install/bin/pidof
rm _install/bin/printenv
rm _install/bin/ps
rm _install/bin/pwd
rm _install/bin/rm
rm _install/bin/rmdir
rm _install/bin/sed
rm _install/bin/sleep
rm _install/bin/stat
rm _install/bin/su
rm _install/bin/sh
rm _install/bin/sync
rm _install/bin/touch
rm _install/bin/true
rm _install/bin/umount
rm _install/bin/usleep
rm _install/bin/tar

rm _install/sbin/blockdev
rm _install/sbin/freeramdisk
rm _install/sbin/halt
rm _install/sbin/hwclock
rm _install/sbin/ifconfig
rm _install/sbin/insmod
rm _install/sbin/losetup
rm _install/sbin/lsmod
rm _install/sbin/mkswap
rm _install/sbin/modinfo
rm _install/sbin/pivot_root
rm _install/sbin/poweroff
rm _install/sbin/reboot
rm _install/sbin/rmmod
rm _install/sbin/swapoff
rm _install/sbin/swapon
rm _install/sbin/switch_root
rm _install/sbin/sysctl
rm _install/sbin/vconfig

rm _install/usr/bin/basename
rm _install/usr/bin/bunzip2
rm _install/usr/bin/bzcat
rm _install/usr/bin/cal
rm _install/usr/bin/chrt
rm _install/usr/bin/chvt
rm _install/usr/bin/clear
rm _install/usr/bin/cmp
rm _install/usr/bin/comm
rm _install/usr/bin/cut
rm _install/usr/bin/dirname
rm _install/usr/bin/du
rm _install/usr/bin/eject
rm _install/usr/bin/env
rm _install/usr/bin/expand
rm _install/usr/bin/factor
rm _install/usr/bin/fallocate
rm _install/usr/bin/find
rm _install/usr/bin/flock
rm _install/usr/bin/free
rm _install/usr/bin/ftpget
rm _install/usr/bin/ftpput
rm _install/usr/bin/groups
rm _install/usr/bin/head
rm _install/usr/bin/hexedit
rm _install/usr/bin/id
rm _install/usr/bin/killall
rm _install/usr/bin/less
rm _install/usr/bin/logger
rm _install/usr/bin/logname
rm _install/usr/bin/lsusb
rm _install/usr/bin/md5sum
rm _install/usr/bin/microcom
rm _install/usr/bin/mkfifo
rm _install/usr/bin/mkpasswd
rm _install/usr/bin/nc
rm _install/usr/bin/nl
rm _install/usr/bin/nohup
rm _install/usr/bin/nproc
rm _install/usr/bin/nsenter
rm _install/usr/bin/od
rm _install/usr/bin/passwd
rm _install/usr/bin/paste
rm _install/usr/bin/patch
rm _install/usr/bin/pgrep
rm _install/usr/bin/pkill
rm _install/usr/bin/pmap
rm _install/usr/bin/printf
rm _install/usr/bin/pwdx
rm _install/usr/bin/readlink
rm _install/usr/bin/realpath
rm _install/usr/bin/renice
rm _install/usr/bin/reset
rm _install/usr/bin/seq
rm _install/usr/bin/setfattr
rm _install/usr/bin/setsid
rm _install/usr/bin/sha1sum
rm _install/usr/bin/shred
rm _install/usr/bin/sort
rm _install/usr/bin/split
rm _install/usr/bin/strings
rm _install/usr/bin/tac
rm _install/usr/bin/tail
rm _install/usr/bin/taskset
rm _install/usr/bin/tee
rm _install/usr/bin/test
rm _install/usr/bin/time
rm _install/usr/bin/timeout
rm _install/usr/bin/top
rm _install/usr/bin/truncate
rm _install/usr/bin/tty
rm _install/usr/bin/uniq
rm _install/usr/bin/unlink
rm _install/usr/bin/unshare
rm _install/usr/bin/uptime
rm _install/usr/bin/uudecode
rm _install/usr/bin/uuencode
rm _install/usr/bin/w
rm _install/usr/bin/wc
rm _install/usr/bin/which
rm _install/usr/bin/who
rm _install/usr/bin/whoami
rm _install/usr/bin/xargs
rm _install/usr/bin/xxd
rm _install/usr/bin/yes

rm _install/usr/sbin/chroot
rm _install/usr/sbin/fsfreeze

rm _install/usr/bin/man

cp -r ./_install/* $SYSROOT

touch $REPO_ROOT/.busybox
