#!/bin/sh

stat $REPO_ROOT/.boot-libcxxabi >/dev/null 2>/dev/null \
&& exit 0

mkdir -p $BUILD/libcxxabi-$LLVM_VER

cd $BUILD/libcxxabi-$LLVM_VER

cmake -G Ninja $SOURCES/llvm-$LLVM_VER/libcxxabi \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_C_FLAGS_INIT='--rtlib=compiler-rt' \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS_INIT='--rtlib=compiler-rt --stdlib=libc++ --unwind=libunwind' \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_SYSROOT=$CHROOT \
-DLIBCXXABI_ENABLE_ASSERTIONS=ON \
-DLIBCXXABI_USE_COMPILER_RT=ON \
-DLIBCXXABI_USE_LLVM_UNWINDER=ON \
-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_SHARED_LIBRARY=YES \
-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=YES \
-DLIBCXXABI_ENABLE_SHARED=OFF \
-DLIBCXXABI_ENABLE_STATIC=ON \
-DLIBCXXABI_INSTALL_LIBRARY=ON



$NINJA

DESTDIR=$CHROOT $NINJA install

cd $REPO_ROOT
touch .boot-libcxxabi
